import User4 from '@/assets/images/user4.jpeg';
import User5 from '@/assets/images/user5.jpeg';
import User6 from '@/assets/images/user6.jpeg';
import User7 from '@/assets/images/user7.jpeg';
import User8 from '@/assets/images/user8.jpeg';
import User9 from '@/assets/images/user9.jpeg';
import User10 from '@/assets/images/user10.jpeg';
import User11 from '@/assets/images/user11.jpeg';

export const RecentCallsData = [
  {
    id: 1,
    name: 'Programmer',
    profileImg: User5,
    time: 'June 15, 6:32 PM',
    incoming: true,
    outgoing: false,
    video: true,
    audio: false,
  },
  {
    id: 2,
    name: 'Meow',
    profileImg: User6,
    time: 'Yesterday, 9:43 PM',
    incoming: false,
    outgoing: true,
    video: true,
    audio: false,
  },
  {
    id: 3,
    name: 'Bro',
    profileImg: User7,
    time: 'Today, 6:32 PM',
    incoming: true,
    outgoing: false,
    video: true,
    audio: false,
  },
  {
    id: 4,
    name: 'Om',
    profileImg: User8,
    time: 'May 2, 9:43 PM',
    incoming: true,
    outgoing: false,
    video: false,
    audio: true,
  },
  {
    id: 5,
    name: 'Jay',
    profileImg: User9,
    time: 'April 16, 6:32 PM',
    incoming: false,
    outgoing: true,
    audio: true,
    video: false,
  },
  {
    id: 6,
    name: 'Siddhi',
    profileImg: User10,
    time: 'Feb 3, 9:43 PM',
    incoming: true,
    outgoing: false,
    audio: false,
    video: true,
  },
  {
    id: 7,
    name: 'Jennie',
    profileImg: User4,
    time: 'Feb 2, 6:32 PM',
    incoming: false,
    outgoing: true,
    audio: true,
    video: false,
  },
  {
    id: 8,
    name: 'Utsav',
    profileImg: User11,
    time: 'Jan 20, 9:43 PM',
    incoming: false,
    outgoing: true,
    audio: false,
    video: true,
  },
  {
    id: 9,
    name: 'Jay',
    profileImg: User9,
    time: 'April 16, 6:32 PM',
    incoming: false,
    outgoing: true,
    audio: true,
    video: false,
  },
  {
    id: 10,
    name: 'Siddhi',
    profileImg: User10,
    time: 'Feb 3, 9:43 PM',
    incoming: true,
    outgoing: false,
    audio: false,
    video: true,
  },
  {
    id: 11,
    name: 'Jennie',
    profileImg: User4,
    time: 'Feb 2, 6:32 PM',
    incoming: false,
    outgoing: true,
    audio: true,
    video: false,
  },
  {
    id: 12,
    name: 'Utsav',
    profileImg: User11,
    time: 'Jan 20, 9:43 PM',
    incoming: false,
    outgoing: true,
    audio: false,
    video: true,
  },
  {
    id: 13,
    name: 'Jay',
    profileImg: User9,
    time: 'April 16, 6:32 PM',
    incoming: false,
    outgoing: true,
    audio: true,
    video: false,
  },
  {
    id: 14,
    name: 'Siddhi',
    profileImg: User10,
    time: 'Feb 3, 9:43 PM',
    incoming: true,
    outgoing: false,
    audio: false,
    video: true,
  },
  {
    id: 15,
    name: 'Jennie',
    profileImg: User4,
    time: 'Feb 2, 6:32 PM',
    incoming: false,
    outgoing: true,
    audio: true,
    video: false,
  },
  {
    id: 16,
    name: 'Utsav',
    profileImg: User11,
    time: 'Jan 20, 9:43 PM',
    incoming: false,
    outgoing: true,
    audio: false,
    video: true,
  },
  {
    id: 17,
    name: 'Jay',
    profileImg: User9,
    time: 'April 16, 6:32 PM',
    incoming: false,
    outgoing: true,
    audio: true,
    video: false,
  },
  {
    id: 18,
    name: 'Siddhi',
    profileImg: User10,
    time: 'Feb 3, 9:43 PM',
    incoming: true,
    outgoing: false,
    audio: false,
    video: true,
  },
  {
    id: 19,
    name: 'Jennie',
    profileImg: User4,
    time: 'Feb 2, 6:32 PM',
    incoming: false,
    outgoing: true,
    audio: true,
    video: false,
  },
  {
    id: 20,
    name: 'Utsav',
    profileImg: User11,
    time: 'Jan 20, 9:43 PM',
    incoming: false,
    outgoing: true,
    audio: false,
    video: true,
  },
];